### ISSUE TITLE
Regex when reading aws profiles from credential file limits to whole words only

### ISSUE THREAD

**Issue by blotto** [terraform-community-modules/tf_aws_availability_zones#7]
For profiles with hyphens, underscores, etc.  the regex pattern will ignore those profiles

``` ruby
# getvariables.rb
next unless l.gsub!(/^\[\s*(\w+)\s*\].*/, '\1')
```
- "prod", "staging" :+1: 
- "test-me" :-1: 

recommend

``` ruby
# getvariables.rb
next unless l.gsub!(/^\[\s*(.*?)\s*\].*/, '\1')
```
- "prod", "staging", "test-me" :+1: 

kept the white-space patterns before and after the capture group.

**Comment by bobtfish** [comment]
Thanks for the bug report and PR!
